/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salacomputocentro.ba
 */
public class Principal extends javax.swing.JFrame {

    public ArrayList<Conductor> IngresarConductor = new ArrayList<>();
    public ArrayList<Personas> transPersonas = new ArrayList<>();
    public ArrayList<Mercancia> transMerc = new ArrayList<>();
    public ArrayList<MercanciaPeligrosa> transMercPeligrosa = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        getContentPane().setBackground(Color.CYAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        TP = new javax.swing.JRadioButton();
        TM = new javax.swing.JRadioButton();
        TMP = new javax.swing.JRadioButton();
        ASIGNAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        IDCON = new javax.swing.JTextField();
        H = new javax.swing.JLabel();
        HORAS = new javax.swing.JTextField();
        CT = new javax.swing.JLabel();
        CANTIDAD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLATP = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        IDCONDU = new javax.swing.JTextField();
        CONSULTAR = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NOMBREC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AGREGAR = new javax.swing.JButton();
        VERCOND = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaN = new javax.swing.JTable();
        VER = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TABLASUEL = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IDCOND = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO TRANSPORTE"));

        buttonGroup1.add(TP);
        TP.setText("Transporte de personas");
        TP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TPStateChanged(evt);
            }
        });
        TP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPActionPerformed(evt);
            }
        });
        TP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TPKeyTyped(evt);
            }
        });

        buttonGroup1.add(TM);
        TM.setText("Transporte de mercancía");
        TM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TMStateChanged(evt);
            }
        });

        buttonGroup1.add(TMP);
        TMP.setText("Transporte de mercancías peligrosas");
        TMP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TMPStateChanged(evt);
            }
        });
        TMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TM, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TMP, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TMP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        ASIGNAR.setText("ASIGNAR");
        ASIGNAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASIGNARActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel7.setText("ASIGNAR TRANSPORTE A CONDUCTOR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("ID CONDUCTOR");

        H.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        H.setText("HORAS");

        HORAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HORASActionPerformed(evt);
            }
        });

        CT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CT.setText("CARGA");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CT)
                    .addComponent(H)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDCON, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                            .addComponent(HORAS))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CANTIDAD))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDCON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HORAS, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CT))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(721, 721, 721)
                        .addComponent(ASIGNAR, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel7)))
                .addContainerGap(998, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ASIGNAR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("ASIGNAR TRANSPORTE A CONDUCTOR", jPanel2);

        TABLATP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "HORAS", "TONELADAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TABLATP);

        jButton4.setText("VER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel8.setText("TRANSPORTES PELIGROSOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("LISTAR TRANSPORTES PELIGROSOS", jPanel3);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("ID CONDUCTOR");

        CONSULTAR.setText("CONSULTAR");
        CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTARActionPerformed(evt);
            }
        });

        TablaT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TIPO DE TRANSPORTE", "HORAS", "CARGA"
            }
        ));
        jScrollPane4.setViewportView(TablaT);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        jLabel9.setText("CONSULTAR TRANSPORTE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(IDCONDU, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel9)))
                .addContainerGap(1077, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDCONDU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("CONSULTAR TRANSPORTE", jPanel6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 85)); // NOI18N
        jLabel3.setText("AGREGAR CONDUCTOR");

        AGREGAR.setText("AGREGAR");
        AGREGAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AGREGARMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AGREGARMouseReleased(evt);
            }
        });
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });

        VERCOND.setText("VER CONDUCTORES");
        VERCOND.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VERCOND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VERCONDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                VERCONDMouseReleased(evt);
            }
        });
        VERCOND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERCONDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(AGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(VERCOND))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDC, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOMBREC, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242)))
                .addContainerGap(1007, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(NOMBREC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VERCOND, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("AGREGAR CONDUCTOR", jPanel1);

        TablaN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "SUELDO BASE", "EXTRAS", "SUELDO TOTAL"
            }
        ));
        jScrollPane3.setViewportView(TablaN);

        VER.setText("VER");
        VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel10.setText("NÓMINA COMPLETA DE LA EMPRESA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(946, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(VER, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(700, 700, 700))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VER, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("VER NÓMINA COMPLETA", jPanel5);

        jButton1.setText("VER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TABLASUEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "SUELDO TOTAL"
            }
        ));
        jScrollPane5.setViewportView(TABLASUEL);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel12.setText("SUELDOS POR EMPLEADO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel12)))
                .addContainerGap(1198, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("VER SUELDOS", jPanel4);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setText("CANTIDAD DE TRANSPORTES POR CONDUCTOR");

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("ID CONDUCTOR");

        jButton3.setText("VER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDCOND, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDCOND, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel11))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(942, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("CANTIDAD DE TRANSPORTES POR CONDUCTOR", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPActionPerformed

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed
        // TODO add your handling code here:

        if (IDC.getText() == null || NOMBREC.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar información en los campos");
        } else {
            int id = Integer.parseInt(IDC.getText());
            String N = NOMBREC.getText();

            IngresarConductor.add(new Conductor(id, N));
            JOptionPane.showMessageDialog(null, "AGREGADO");
        }
        IDC.setText("");
        NOMBREC.setText("");
    }//GEN-LAST:event_AGREGARActionPerformed

    private void ASIGNARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASIGNARActionPerformed
        // TODO add your handling code here:

        //variables
        int cant = Integer.parseInt(CANTIDAD.getText());
        int horas = Integer.parseInt(HORAS.getText());
        int id = Integer.parseInt(IDCON.getText());
        boolean c = true;

        for (int i = 0; i < IngresarConductor.size(); i++) {

            if (IngresarConductor.get(i).getId() == id) {
                c = false;
                if (TP.isSelected()) {

                    transPersonas.add(new Personas(cant, horas, id));
                    JOptionPane.showMessageDialog(null, "ASIGNADO");

                } else if (TM.isSelected()) {

                    transMerc.add(new Mercancia(cant, horas, id));
                    JOptionPane.showMessageDialog(null, "ASIGNADO");

                } else if (TMP.isSelected()) {

                    transMercPeligrosa.add(new MercanciaPeligrosa(cant, horas, id));
                    JOptionPane.showMessageDialog(null, "ASIGNADO");

                }
            }

        } //Termina for
        if (c) {
            JOptionPane.showMessageDialog(null, "Conductor no existente", "ERROR", HEIGHT);
        }
        IDCON.setText("");
        CANTIDAD.setText("");
        HORAS.setText("");

    }//GEN-LAST:event_ASIGNARActionPerformed

    private void TPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_TPKeyReleased

    private void TPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TPKeyPressed

    private void TPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_TPKeyTyped

    private void TPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TPStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_TPStateChanged

    private void TMStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TMStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_TMStateChanged

    private void VERCONDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERCONDActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < IngresarConductor.size(); i++) {

            JOptionPane.showMessageDialog(null, "\nCONDUCTORES"
                    + "\nID : " + IngresarConductor.get(i).getId()
                    + "\nNOMBRE : " + IngresarConductor.get(i).getNombre());
        }


    }//GEN-LAST:event_VERCONDActionPerformed

    private void TMPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TMPStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_TMPStateChanged

    private void VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERActionPerformed
        // TODO add your handling code here:
        int x = transPersonas.size() + transMerc.size() + transMercPeligrosa.size();
        String col[] = {"ID", "SUELDO BASE", "EXTRAS", "TIPO TRANSPORTE", "HORAS", "CARGA"};
        String t[][] = new String[x][6];
        for (int i = 0; i < transPersonas.size(); i++) {
            transPersonas.get(i).CalcularSP();
            t[i][0] = Integer.toString(transPersonas.get(i).getIdC());
            t[i][1] = Integer.toString(1550000);
            t[i][2] = Double.toString(transPersonas.get(i).getSueldo());
            t[i][3] = transPersonas.get(i).getTipoTransporte();
            t[i][4] = Integer.toString(transPersonas.get(i).getHorasConducidas());
            t[i][5] = Integer.toString(transPersonas.get(i).getCantidadPersonas());
        }

        for (int i = 0; i < transMerc.size(); i++) {
            transMerc.get(i).CalcularSM();

            t[i + transPersonas.size()][0] = Integer.toString(transMerc.get(i).getIdC());
            t[i + transPersonas.size()][1] = Integer.toString(1550000);
            t[i + transPersonas.size()][2] = Double.toString(transMerc.get(i).getSueldo());
            t[i + transPersonas.size()][3] = transMerc.get(i).getTipoTransporte();
            t[i + transPersonas.size()][4] = Integer.toString(transMerc.get(i).getHorasConducidas());
            t[i + transPersonas.size()][5] = Double.toString(transMerc.get(i).getToneladas());
        }

        for (int i = 0; i < transMercPeligrosa.size(); i++) {
            transMercPeligrosa.get(i).CalcularSMP();
            t[i + transPersonas.size() + transMerc.size()][0] = Integer.toString(transMercPeligrosa.get(i).getIdC());
            t[i + transPersonas.size() + transMerc.size()][1] = Integer.toString(1550000);
            t[i + transPersonas.size() + transMerc.size()][2] = Double.toString(transMercPeligrosa.get(i).getSueldo());
            t[i + transPersonas.size() + transMerc.size()][3] = transMercPeligrosa.get(i).getTipoTransporte();
            t[i + transPersonas.size() + transMerc.size()][4] = Integer.toString(transMercPeligrosa.get(i).getHorasConducidas());
            t[i + transPersonas.size() + transMerc.size()][5] = Double.toString(transMercPeligrosa.get(i).getToneladas());

        }

        TablaN.setModel(new DefaultTableModel(t, col));
    }//GEN-LAST:event_VERActionPerformed

    private void CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTARActionPerformed
        // TODO add your handling code here:

        int x = transPersonas.size() + transMerc.size() + transMercPeligrosa.size();
        int id = Integer.parseInt(IDCONDU.getText());
        String col[] = {"TIPO DE TRANSPORTE", "HORAS", "CARGA"};
        String matriz[][] = new String[x][3];
        for (int i = 0; i < transPersonas.size(); i++) {
            if (transPersonas.get(i).getIdC() == id) {
                matriz[i][0] = transPersonas.get(i).getTipoTransporte();
                matriz[i][1] = Double.toString(transPersonas.get(i).getHorasConducidas());
                matriz[i][2] = Double.toString(transPersonas.get(i).getCantidadPersonas());
            }
        }
        TablaT.setModel(new DefaultTableModel(matriz, col));

        for (int i = 0; i < transMerc.size(); i++) {
            if (transMerc.get(i).getIdC() == id) {
                int y = i + transPersonas.size();
                matriz[y][0] = transMerc.get(i).getTipoTransporte();
                matriz[y][1] = Double.toString(transMerc.get(i).getHorasConducidas());
                matriz[y][2] = Double.toString(transMerc.get(i).getToneladas());
            }
        }
        TablaT.setModel(new DefaultTableModel(matriz, col));

        for (int i = 0; i < transMercPeligrosa.size(); i++) {
            if (transMercPeligrosa.get(i).getIdC() == id) {
                int y = i + transPersonas.size() + transMerc.size();
                matriz[y][0] = transMercPeligrosa.get(i).getTipoTransporte();
                matriz[y][1] = Double.toString(transMercPeligrosa.get(i).getHorasConducidas());
                matriz[y][2] = Double.toString(transMercPeligrosa.get(i).getToneladas());
            }
        }
        TablaT.setModel(new DefaultTableModel(matriz, col));
    }//GEN-LAST:event_CONSULTARActionPerformed

    private void HORASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HORASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HORASActionPerformed

    private void TMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMPActionPerformed

    private void AGREGARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGREGARMousePressed
        // TODO add your handling code here:
        AGREGAR.setBackground(Color.white);


    }//GEN-LAST:event_AGREGARMousePressed

    private void VERCONDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERCONDMousePressed
        // TODO add your handling code here:

        VERCOND.setBackground(Color.cyan);
    }//GEN-LAST:event_VERCONDMousePressed

    private void AGREGARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AGREGARMouseReleased
        // TODO add your handling code here:

        AGREGAR.setBackground(Color.cyan);
    }//GEN-LAST:event_AGREGARMouseReleased

    private void VERCONDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VERCONDMouseReleased
        // TODO add your handling code here:
        VERCOND.setBackground(Color.white);
    }//GEN-LAST:event_VERCONDMouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String col[] = {"ID", "HORAS", "TONELADAS"};
        String matriz[][] = new String[transMercPeligrosa.size()][3];
        for (int i = 0; i < transMercPeligrosa.size(); i++) {
            matriz[i][0] = Integer.toString(transMercPeligrosa.get(i).getIdC());
            matriz[i][1] = Integer.toString(transMercPeligrosa.get(i).getHorasConducidas());
            matriz[i][2] = Double.toString(transMercPeligrosa.get(i).getToneladas());

        }
        TABLATP.setModel(new DefaultTableModel(matriz, col));

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x = transPersonas.size() + transMerc.size() + transMercPeligrosa.size();
        String col[] = {"ID", "SUELDO TOTAL"};
        String matriz[][] = new String[x][2];
        for (int i = 0; i < IngresarConductor.size(); i++) {
            matriz[i][0] = Integer.toString(IngresarConductor.get(i).getId());
            matriz[i][1] = Double.toString(listarSueldos(IngresarConductor.get(i).getId()));
        }
        TABLASUEL.setModel(new DefaultTableModel(matriz, col));

    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int acumulador = 0;
        boolean c = true;
        int id = Integer.parseInt(IDCOND.getText());

        for (int i = 0; i < IngresarConductor.size(); i++) {
            if (IngresarConductor.get(i).getId() == id) {
                c = false;
                break;
            }
        }
        if (c == false) {
            for (int i = 0; i < transPersonas.size(); i++) {
                if (transPersonas.get(i).getIdC() == id) {
                    acumulador++;
                }
            }
            for (int i = 0; i < transMerc.size(); i++) {
                if (transMerc.get(i).getIdC() == id) {
                    acumulador++;
                }
            }
            for (int i = 0; i < transMercPeligrosa.size(); i++) {
                if (transMercPeligrosa.get(i).getIdC() == id) {
                    acumulador++;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Cantidad de transportes: " + acumulador);

       
    }//GEN-LAST:event_jButton3ActionPerformed

    public double listarSueldos(int id) {

        double sueldoExtra = 0;

        for (int i = 0; i < transPersonas.size(); i++) {

            if (id == transPersonas.get(i).getIdC()) {

                sueldoExtra += transPersonas.get(i).getSueldo();
            }
        }
        for (int i = 0; i < transMerc.size(); i++) {

            if (id == transMerc.get(i).getIdC()) {

                sueldoExtra += transMerc.get(i).getSueldo();
            }
        }
        for (int i = 0; i < transMercPeligrosa.size(); i++) {

            if (id == transMercPeligrosa.get(i).getIdC()) {

                sueldoExtra += transMercPeligrosa.get(i).getSueldo();
            }
        }

        return sueldoExtra + 1550000;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JButton ASIGNAR;
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JButton CONSULTAR;
    private javax.swing.JLabel CT;
    private javax.swing.JLabel H;
    private javax.swing.JTextField HORAS;
    private javax.swing.JTextField IDC;
    private javax.swing.JTextField IDCON;
    private javax.swing.JTextField IDCOND;
    private javax.swing.JTextField IDCONDU;
    private javax.swing.JTextField NOMBREC;
    private javax.swing.JTable TABLASUEL;
    private javax.swing.JTable TABLATP;
    private javax.swing.JRadioButton TM;
    private javax.swing.JRadioButton TMP;
    private javax.swing.JRadioButton TP;
    private javax.swing.JTable TablaN;
    private javax.swing.JTable TablaT;
    private javax.swing.JButton VER;
    private javax.swing.JButton VERCOND;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
