package empresa.agroalimentaria;

import java.util.*;

public class EmpresaAgroalimentaria {

    public static void main(String[] args) {
        Scanner read = new Scanner(System.in);
        int dia1, mes1, año1, dia, mes, año, dia2, mes2, año2, dia3, mes3, año3, nlote;
        double temp;
        long codigo;
        String pais;
        System.out.println("Digite fecha de caducidad 1er producto fresco");
        System.out.println("Dia");
        dia = read.nextInt();
        System.out.println("Mes");
        mes = read.nextInt();
        System.out.println("Año");
        año = read.nextInt();
        System.out.println("Digite País");
        pais = read.next();
        System.out.println("Digite fecha de envasado 1er producto fresco");
        System.out.println("Dia");
        dia1 = read.nextInt();
        System.out.println("Mes");
        mes1 = read.nextInt();
        System.out.println("Año");
        año1 = read.nextInt();
        System.out.println("Digite número de lote");
        nlote = read.nextInt();
        System.out.println("");
        System.out.println("");
        Productos_frescos pf1 = new Productos_frescos(dia1, mes1, año1, pais, dia, mes, año, nlote);
        System.out.println("");
        System.out.println("");
        System.out.println("Digite fecha de caducidad 2er producto fresco");
        System.out.println("Dia");
        dia = read.nextInt();
        System.out.println("Mes");
        mes = read.nextInt();
        System.out.println("Año");
        año = read.nextInt();
        System.out.println("Digite País");
        pais = read.next();
        System.out.println("");
        System.out.println("Digite fecha de envasado 2do producto fresco");
        System.out.println("Dia");
        dia1 = read.nextInt();
        System.out.println("Mes");
        mes1 = read.nextInt();
        System.out.println("Año");
        año1 = read.nextInt();
        System.out.println("Digite número de lote");
        nlote = read.nextInt();
        System.out.println("");
        System.out.println("");
        Productos_frescos pf2 = new Productos_frescos(dia1, mes1, año1, pais, dia, mes, año, nlote);
        System.out.println("");
        System.out.println("");
        System.out.println("Digite fecha de caducidad 1er producto refrigerado");
        System.out.println("Dia");
        dia = read.nextInt();
        System.out.println("Mes");
        mes = read.nextInt();
        System.out.println("Año");
        año = read.nextInt();
        System.out.println("Digite País");
        pais = read.next();
        System.out.println("");
        System.out.println("Digite fecha de envasado 1er producto refrigerado");
        System.out.println("Dia");
        dia2 = read.nextInt();
        System.out.println("Mes");
        mes2 = read.nextInt();
        System.out.println("Año");
        año2 = read.nextInt();
        System.out.println("Digite número de lote");
        nlote = read.nextInt();
        System.out.println("Digite temperatura");
        temp = read.nextDouble();
        System.out.println("Digite el código del organismo de supervisión alimentaria");
        codigo = read.nextLong();
        System.out.println("");
        System.out.println("");
        Productos_refrigerados pr1 = new Productos_refrigerados(codigo, dia2, mes2, año2, temp, pais, dia, mes, año, nlote);
        System.out.println("");
        System.out.println("");
        System.out.println("Digite fecha de caducidad 1er producto refrigerado");
        System.out.println("Dia");
        dia = read.nextInt();
        System.out.println("Mes");
        mes = read.nextInt();
        System.out.println("Año");
        año = read.nextInt();
        System.out.println("Digite País");
        pais = read.next();
        System.out.println("");
        System.out.println("Digite fecha de envasado 1er producto refrigerado");
        System.out.println("Dia");
        dia2 = read.nextInt();
        System.out.println("Mes");
        mes2 = read.nextInt();
        System.out.println("Año");
        año2 = read.nextInt();
        System.out.println("Digite número de lote");
        nlote = read.nextInt();
        System.out.println("Digite temperatura");
        temp = read.nextDouble();
        System.out.println("Digite el código del organismo de supervisión alimentaria");
        codigo = read.nextLong();
        System.out.println("");
        System.out.println("");
        Productos_refrigerados pr2 = new Productos_refrigerados(codigo, dia2, mes2, año2, temp, pais, dia, mes, año, nlote);
        pf1.datosfrescos();
        pf2.datosfrescos();
        pr1.datosrefri();
        pr2.datosrefri();
        
    }

}
