/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parciall;

import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.time.temporal.ValueRange;

import javax.swing.JPanel;

/**
 *
 * @author FAMILIA ESCORCIA
 */
public class principal extends javax.swing.JFrame {

    Almacen a = new Almacen();
    reporteventa rp = new reporteventa();

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        getContentPane().setBackground(Color.CYAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        AgregarProducto = new javax.swing.JButton();
        CantidadP = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PrecioP = new javax.swing.JTextField();
        CodigoP = new javax.swing.JTextField();
        NombreP = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        mostrarproduc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        Codigopbaja = new javax.swing.JTextField();
        DarDeBaja1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        realizarV = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        vueltoV = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        CodigoProductoV = new javax.swing.JTextField();
        prodV = new javax.swing.JTextField();
        precioV = new javax.swing.JTextField();
        cantidadV = new javax.swing.JTextField();
        efectivoV = new javax.swing.JTextField();
        totalaPV = new javax.swing.JTextField();
        fecha = new javax.swing.JLabel();
        fechaV = new javax.swing.JTextField();
        Tventas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoRP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cantidadRP = new javax.swing.JTextField();
        reducir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        codigoAP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadAP = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        FechaReporteD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IR = new javax.swing.JButton();
        IR2 = new javax.swing.JButton();
        IR3 = new javax.swing.JButton();
        DiaSemanaR = new javax.swing.JTextField();
        NumeroMesRM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NumeroAñoRM1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        codINV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        presupuesto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fechaINV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        descripcionINV = new javax.swing.JTextField();
        invertir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("TIENDA DE ROPA");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESO DE PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel29.setText("Código de producto a ingresar");

        AgregarProducto.setText("AGREGAR PRODUCTO");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });

        jLabel26.setText("Cantidad");

        jLabel27.setText("Precio");

        PrecioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioPActionPerformed(evt);
            }
        });

        NombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePActionPerformed(evt);
            }
        });

        jLabel28.setText("Nombre de producto a ingresar");

        mostrarproduc.setText("MOSTRAR PRODUCTOS");
        mostrarproduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarproducActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PrecioP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CantidadP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(AgregarProducto)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostrarproduc))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(CodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(PrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(CantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(mostrarproduc))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DAR DE BAJA A PRODUCTOS EN SU TOTALIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel70.setText("Código de producto a dar de baja");

        DarDeBaja1.setText("DAR DE BAJA");
        DarDeBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarDeBaja1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DarDeBaja1)
                            .addComponent(Codigopbaja, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Codigopbaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DarDeBaja1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        realizarV.setText("VENDER!");
        realizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVActionPerformed(evt);
            }
        });

        jButton4.setText("ATRÁS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        vueltoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltoVActionPerformed(evt);
            }
        });

        jLabel71.setText("Devuelta");

        jLabel72.setText("Total a pagar");

        jLabel73.setText("Efectivo");

        jLabel74.setText("Cantidad");

        jLabel75.setText("Precio");

        jLabel76.setText("Producto");

        jLabel77.setText("Código producto");

        CodigoProductoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoProductoVActionPerformed(evt);
            }
        });
        CodigoProductoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoProductoVKeyReleased(evt);
            }
        });

        cantidadV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadVActionPerformed(evt);
            }
        });
        cantidadV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadVKeyReleased(evt);
            }
        });

        efectivoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoVActionPerformed(evt);
            }
        });
        efectivoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                efectivoVKeyReleased(evt);
            }
        });

        fecha.setText("Fecha (AAAA-MM-DD)");

        fechaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaVActionPerformed(evt);
            }
        });

        Tventas.setText("Total de ventas");
        Tventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TventasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel74)
                            .addComponent(jLabel75)
                            .addComponent(jLabel76)
                            .addComponent(jLabel77)
                            .addComponent(jLabel73)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fecha)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(efectivoV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(cantidadV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodigoProductoV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaV, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(realizarV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(totalaPV, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(vueltoV)))
                        .addGap(52, 52, 52)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Tventas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel72)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha)
                            .addComponent(fechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(CodigoProductoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel76)
                            .addComponent(prodV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalaPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel71)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(precioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(vueltoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74)
                    .addComponent(jButton4)
                    .addComponent(realizarV))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel73)
                            .addComponent(efectivoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Tventas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REDUCIR EXISTENCIA DE PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("Código de producto que va a reducir");

        jLabel3.setText("Cantidad a disminuir");

        cantidadRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadRPActionPerformed(evt);
            }
        });

        reducir.setText("REDUCIR");
        reducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(reducir))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(codigoRP)
                        .addComponent(cantidadRP, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reducir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGREGAR EXISTENCIA DE PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel4.setText("Código de producto que va a incrementar");

        jLabel5.setText("Cantidad a incrementar");

        cantidadAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAPActionPerformed(evt);
            }
        });

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigoAP)
                    .addComponent(cantidadAP, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(agregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("REPORTE DIARIO");

        jLabel7.setText("Ingrese la fecha (YYYY-MM-DD)");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("REPORTE SEMANAL");

        jLabel9.setText("Ingrese el día (DD)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("REPORTE MENSUAL");

        IR.setText("IR");
        IR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRActionPerformed(evt);
            }
        });

        IR2.setText("IR");
        IR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IR2ActionPerformed(evt);
            }
        });

        IR3.setText("IR");
        IR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IR3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingrese el mes (MM)");

        jLabel16.setText("Ingrese el año (YYYY)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumeroMesRM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(NumeroAñoRM1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(IR3)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(DiaSemanaR, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IR2))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(FechaReporteD, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(IR))
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaReporteD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IR))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaSemanaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IR2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroMesRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroAñoRM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IR3))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVERSIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel12.setText("Código de inversión");

        jLabel13.setText("Presupuesto");

        jLabel14.setText("Fecha");

        jLabel15.setText("Descripción");

        invertir.setText("INVERTIR");
        invertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirActionPerformed(evt);
            }
        });

        jButton1.setText("VER INVERSIONES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GANANCIAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codINV)
                            .addComponent(presupuesto)
                            .addComponent(fechaINV)
                            .addComponent(descripcionINV, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(invertir)
                .addGap(105, 105, 105))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(codINV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fechaINV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(descripcionINV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(invertir)
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
        // TODO add your handling code here:

        //ACCION PARA AGREGAR PRODUCTOS A LISTA
        //entra aqui por si algunos de los campos están vacíos
        if (CodigoP.getText() == null || NombreP.getText() == null || PrecioP.getText() == null || CantidadP.getText() == null) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser rellenados para poder ingresar el producto a sistema");
        } else {   //si todo está bien entrá acá
            int id = Integer.parseInt(CodigoP.getText());
            String nombre = NombreP.getText();
            double precio = Double.parseDouble(PrecioP.getText());
            int cantidad = Integer.parseInt(CantidadP.getText());

            a.AgregarProducto(id, nombre, precio, cantidad); //Acción que agrega productos
            CodigoP.setText("");
            NombreP.setText("");
            PrecioP.setText("");
            CantidadP.setText("");

        }


    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void NombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePActionPerformed

    private void PrecioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioPActionPerformed

    private void DarDeBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DarDeBaja1ActionPerformed
        // TODO add your handling code here:

        //ACCION PARA DAR DE BAJA POR COMPLETO A UN PRODUCTO DE LA LISTA
        int cod = Integer.parseInt(Codigopbaja.getText());
        boolean x = false;

        //AQUI MIRAMOS QUE EL PRODUCTO ESTÉ EN LA LISTA
        for (int i = 0; i < a.getIngresarStock().size(); i++) {
            if (cod == a.getIngresarStock().get(i).getId()) {
                a.Dar_de_bajaProducto(i);
                Codigopbaja.setText("");
                x = true;
                break;
            }
        }

        //SI NO ESTÁ NOS MOSTRARÁ ESTE MENSAJE
        if (x == false) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado");

        }

    }//GEN-LAST:event_DarDeBaja1ActionPerformed

    private void realizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVActionPerformed
        // TODO add your handling code here:

        //ACCION PARA INGRESAR LA VENTA A LA LISTA
        boolean conf = false; //para confirmar si el producto esta en la lista
        int codV = Integer.parseInt(CodigoProductoV.getText());
        int cprod = Integer.parseInt(CodigoProductoV.getText());
        String nom = prodV.getText();
        double prec = Double.parseDouble(precioV.getText());

        //SI LA LISTA ESTÀ VACIA ENTRA AQUI SINO EJECUTA LA ACCION
        if (fechaV.getText() == "" || CodigoProductoV.getText() == "" || cantidadV.getText() == "" || efectivoV.getText() == "" || vueltoV.getText() == "" || prodV.getText() == "" || cantidadV.getText() == "" || precioV.getText() == "" || totalaPV.getText() == "") {
            JOptionPane.showMessageDialog(null, "Todos los campos deben ser rellenados para poder ingresar el producto a sistema");
        } else {

            for (int i = 0; i < a.getIngresarStock().size(); i++) {

                if (codV == a.getIngresarStock().get(i).getId()) {

                    if (a.getIngresarStock().get(i).getCantidad() == 0) { // SI LA CANTIDAD DE PRODUCTO EN LA LISTA ES IGUAL A 0 NO SE REALIZA LA VENTA
                        JOptionPane.showMessageDialog(null, "No hay existencia del producto que quiere vender, ingrese!!");
                    } else if (a.getIngresarStock().get(i).getCantidad() > 0) {
                        LocalDate fechal = LocalDate.parse(fechaV.getText());
                        int cant = Integer.parseInt(cantidadV.getText());
                        double total = Double.parseDouble(totalaPV.getText());
                        double efect = Double.parseDouble(efectivoV.getText());
                        int id = i;
                        double vuelto = Double.parseDouble(vueltoV.getText());

                        productos produc = new productos(cprod, nom, prec, cant);
                        venta ventas = new venta(produc, total, efect, cant, id, vuelto, fechal);
                        cantidadV.setText("");
                        totalaPV.setText("");
                        vueltoV.setText("");
                        efectivoV.setText("");
                        a.AgregarVentas(ventas);
                        ventas.ImprimirFactura();
                        a.getIngresarStock().get(i).Rcantidad(cant);
                        a.getIngresarStock().get(i).notificar();
                        conf = true;
                        break;

                    }

                }
                //else if (codV != a.getIngresarStock().get(i).getId()) {
                   // JOptionPane.showMessageDialog(null, "Producto no encontrado en la bases de datos de los productos");
                //}

            }
            if (conf == false) {
                JOptionPane.showMessageDialog(null, "Producto no encontrado en la bases de datos de los productos");
                cantidadV.setText("");
                totalaPV.setText("");
                vueltoV.setText("");
                efectivoV.setText("");
                prodV.setText("");
                CodigoProductoV.setText("");
                fechaV.setText("");
                precioV.setText("");
           }

        }


    }//GEN-LAST:event_realizarVActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void vueltoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueltoVActionPerformed

    private void CodigoProductoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoProductoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoProductoVActionPerformed

    private void CodigoProductoVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProductoVKeyReleased
        // TODO add your handling code here:

        //ACCION PARA MOSTRAR LOS VALORES DEL PRODUCTO EN EL PANEL DE VENTA AUTOMATICAMENTE
        int cod = Integer.parseInt(CodigoProductoV.getText());

        for (int i = 0; i < a.getIngresarStock().size(); i++) {
            if (cod == a.getIngresarStock().get(i).getId()) {
                prodV.setText("" + a.getIngresarStock().get(i).getNombre());
                precioV.setText("" + a.getIngresarStock().get(i).getPrecio());
            }
        }


    }//GEN-LAST:event_CodigoProductoVKeyReleased

    private void cantidadVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadVActionPerformed

    private void cantidadVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadVKeyReleased
        // TODO add your handling code here:

        //ACCION PARA CALCULAR EL TOTAL DE LA VENTA
        int cod = Integer.parseInt(CodigoProductoV.getText());
        int cant = Integer.parseInt(cantidadV.getText());
        double total = 0;
        for (int i = 0; i < a.getIngresarStock().size(); i++) {
            if (cod == a.getIngresarStock().get(i).getId()) {
                total = cant * a.getIngresarStock().get(i).getPrecio();
            }
        }

        totalaPV.setText("" + total);
    }//GEN-LAST:event_cantidadVKeyReleased

    private void efectivoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoVActionPerformed
        // TODO add your handling code here:

        //ACCION POR SI EL EFECTIVO ES MENOR AL MONTO QUE SE DEBE PAGAR
        double tot = Double.parseDouble(totalaPV.getText());
        double efect = Double.parseDouble(efectivoV.getText());

        if (efect < tot) {
            JOptionPane.showMessageDialog(null, "el valor del efectivo es menor del total a pagar");
        }
    }//GEN-LAST:event_efectivoVActionPerformed

    private void efectivoVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_efectivoVKeyReleased
        // TODO add your handling code here:
        //AQUI SE VA A CALCULAR EL VUELTO DE LA VENTA

        double tot = Double.parseDouble(totalaPV.getText());
        double efect = Double.parseDouble(efectivoV.getText());
        double vuelto;

        if (efect >= tot) {
            vuelto = efect - tot;
            vueltoV.setText("" + vuelto);
        }
    }//GEN-LAST:event_efectivoVKeyReleased

    private void mostrarproducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarproducActionPerformed
        // TODO add your handling code here:

        //ACCION PARA QUE MUESTRE LOS PRODUCTOS QUE ESTÁN EN LA LISTA
        if (a.getIngresarStock().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lista de productos vacías, por favor ingrese uno");
        } else {
            for (int i = 0; i < a.getIngresarStock().size(); i++) {

                JOptionPane.showMessageDialog(null, "\nCódigo producto: " + a.getIngresarStock().get(i).getId() + "\nNombre: " + a.getIngresarStock().get(i).getNombre() + "\nPrecio: " + a.getIngresarStock().get(i).getPrecio() + "\nCantidad: " + a.getIngresarStock().get(i).getCantidad());
            }
        }


    }//GEN-LAST:event_mostrarproducActionPerformed

    private void cantidadRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadRPActionPerformed

    private void cantidadAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAPActionPerformed

    private void reducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reducirActionPerformed
        // TODO add your handling code here:

        //ACA SE VA A REDUCIR LA CANTIDAD DE PRODUCTOS DE LA LISTA
        int cod = Integer.parseInt(codigoRP.getText());
        int cant = Integer.parseInt(cantidadRP.getText());
        boolean x = false;
        for (int i = 0; i < a.getIngresarStock().size(); i++) {
            if (cod == a.getIngresarStock().get(i).getId()) {
                a.getIngresarStock().get(i).Rcantidad(cant);
                JOptionPane.showMessageDialog(null, "Cantidad de producto reducida"
                        + "\nNombre del producto: " + a.getIngresarStock().get(i).getNombre()
                        + "\nCantidad actualizada: " + a.getIngresarStock().get(i).getCantidad());
                codigoRP.setText("");
                cantidadRP.setText("");
                a.getIngresarStock().get(i).notificar();
                x = true;
                break;
            }
        }
        if (x == false) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado en la base de datos");
        }
    }//GEN-LAST:event_reducirActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:

        //ACA SE VA A AUMENTAR LA CANTIDAD DE PRODUCTOS DE LA LISTA
        int cod = Integer.parseInt(codigoAP.getText());
        int cant = Integer.parseInt(cantidadAP.getText());
        boolean x = false;
        for (int i = 0; i < a.getIngresarStock().size(); i++) {

            if (cod == a.getIngresarStock().get(i).getId()) {

                a.getIngresarStock().get(i).Acantidad(cant);
                JOptionPane.showMessageDialog(null, "Cantidad de producto agregada"
                        + "\nNombre del producto: " + a.getIngresarStock().get(i).getNombre()
                        + "\nCantidad actualizada: " + a.getIngresarStock().get(i).getCantidad());
                codigoAP.setText("");
                cantidadAP.setText("");
                x = true;
                break;
            }
        }

        if (x == false) {
            JOptionPane.showMessageDialog(null, "Producto no encontrado en la base de datos");
        }

    }//GEN-LAST:event_agregarActionPerformed

    private void fechaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaVActionPerformed

    private void IRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRActionPerformed
        // TODO add your handling code here:

        rp.setReporven(a.getVentas());
        rp.setA(a);
        rp.ReporteDiario(FechaReporteD.getText());

    }//GEN-LAST:event_IRActionPerformed

    private void IR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IR2ActionPerformed
        // TODO add your handling code here:

        rp.setReporven(a.getVentas());
        rp.setA(a);
        rp.ReporteSemanal(DiaSemanaR.getText());
    }//GEN-LAST:event_IR2ActionPerformed

    private void IR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IR3ActionPerformed
        // TODO add your handling code here:

        rp.setReporven(a.getVentas());
        rp.setA(a);

        int nmrm = Integer.parseInt(NumeroMesRM.getText());
        int nmarm = Integer.parseInt(NumeroAñoRM1.getText());

        rp.ReporteMensual(nmrm, nmarm);

    }//GEN-LAST:event_IR3ActionPerformed

    private void invertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirActionPerformed
        // TODO add your handling code here:

        //ACCION QUE REALIZA EL INGRESO DE LAS INVERSIONES EN LA LISTA
        int idInver = Integer.parseInt(codINV.getText());
        double cantInver = Double.parseDouble(presupuesto.getText());
        String descr = descripcionINV.getText();
        LocalDate fechaInv = LocalDate.parse(fechaINV.getText());
        a.agregarInversion(new inversion(cantInver, fechaInv, descr, idInver));

    }//GEN-LAST:event_invertirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < a.getInversiones().size(); i++) {
            JOptionPane.showMessageDialog(null, "La fecha de lainversion: " + a.getInversiones().get(i).getFecha()
                    + "\nEl codigo de la inversion: " + a.getInversiones().get(i).getIdinversion()
                    + "\nLa descripcion de la inversion: " + a.getInversiones().get(i).getDescripcion()
                    + "\nEl total delainversioon es: " + a.getInversiones().get(i).getCantidad()
            );
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //ACCION PARA OBTENER GANANCIAS DE LAS INVERSIONES Y VENTAS QUE SE REALICEN
        double totalinv = 0;
        double totalvent = 0;
        double obtGanancia = 0;
        for (int i = 0; i < a.getInversiones().size(); i++) {
            totalinv += a.getInversiones().get(i).getCantidad();
            for (int j = 0; j < a.getVentas().size(); j++) {
                totalvent += a.getVentas().get(j).getTotal();
            }
        }

        JOptionPane.showMessageDialog(null, "La ganancia total obtenidas es " + a.ObtenerGanancia(totalvent, totalinv, obtGanancia));


    }//GEN-LAST:event_jButton2ActionPerformed

    private void TventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TventasActionPerformed
        // TODO add your handling code here:

        // ACCION PARA MOSTRAR TODAS LAS VENTAS
        for (int i = 0; i < a.getVentas().size(); i++) {
            JOptionPane.showMessageDialog(null,
                    "\nFecha de la venta " + a.getVentas().get(i).getFecha()
                    + "\nCódigo producto : " + a.getVentas().get(i).getProd().getId()
                    + "\nProducto :" + a.getVentas().get(i).getProd().getNombre()
                    + "\nPrecio : " + a.getVentas().get(i).getProd().getPrecio()
                    + "\nCantidad : " + a.getVentas().get(i).getCant()
                    + "\nTotal a pagar :" + a.getVentas().get(i).getTotal()
                    + "\nEfectivo :" + a.getVentas().get(i).getEfectivo()
                    + "\nVuelto :" + a.getVentas().get(i).getVuelto());
        }

        //EN CASO DE QUE ESTE VACIA MUESTRA ESTO
        if (a.getVentas().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ha realizado ninguna venta");
        }


    }//GEN-LAST:event_TventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProducto;
    private javax.swing.JTextField CantidadP;
    private javax.swing.JTextField CodigoP;
    private javax.swing.JTextField CodigoProductoV;
    private javax.swing.JTextField Codigopbaja;
    private javax.swing.JButton DarDeBaja1;
    private javax.swing.JTextField DiaSemanaR;
    private javax.swing.JTextField FechaReporteD;
    private javax.swing.JButton IR;
    private javax.swing.JButton IR2;
    private javax.swing.JButton IR3;
    private javax.swing.JTextField NombreP;
    private javax.swing.JTextField NumeroAñoRM1;
    private javax.swing.JTextField NumeroMesRM;
    private javax.swing.JTextField PrecioP;
    private javax.swing.JButton Tventas;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidadAP;
    private javax.swing.JTextField cantidadRP;
    private javax.swing.JTextField cantidadV;
    private javax.swing.JTextField codINV;
    private javax.swing.JTextField codigoAP;
    private javax.swing.JTextField codigoRP;
    private javax.swing.JTextField descripcionINV;
    private javax.swing.JTextField efectivoV;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fechaINV;
    private javax.swing.JTextField fechaV;
    private javax.swing.JButton invertir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton mostrarproduc;
    private javax.swing.JTextField precioV;
    private javax.swing.JTextField presupuesto;
    private javax.swing.JTextField prodV;
    private javax.swing.JButton realizarV;
    private javax.swing.JButton reducir;
    private javax.swing.JTextField totalaPV;
    private javax.swing.JTextField vueltoV;
    // End of variables declaration//GEN-END:variables
}
